### ISSUE TITLE
Unsure of how to set this up and unaware of how to reach the developer

### ISSUE THREAD

**Issue by MikeMcCracken450** [topeterk/HitCounterManager#15]
Please fill in all relevant data. That's it.
I am trying to set up a hit counter in OBS Studio, but I don't fully understand how to get this to work or show up. If someone can reach out to me to provide a more detailed setup explanation for a Windows 10 PC, I would really appreciate the help.

**Comment by MikeMcCracken450** [comment]
Also can't install the 19.0 version because it wants version 2.0. I have 4.something and it still not work.

**Comment by topeterk** [comment]
Hi, it should run with .Net 2.0 and .Net 4.x as well.
Haven't verified this yet but maybe the installer is checking for the .Net version.
So, can you try using the other zip file without the setup (just extract it where ever you want and run the exe file)?

To add it to OBS Studio, it should be enough to enter the file name into the "browser" source of your scene and check the local file checkbox:
![image](https://user-images.githubusercontent.com/4932525/67814230-d0ba6300-faa3-11e9-9e1f-62274d7d3855.png)
Keep in mind you have to use the HTML file in the Designs folder, not the one next to the exe file.

Hope this helps?

**Comment by topeterk** [comment]
I guess the issue has been resolved, so I close this issue.
