### ISSUE TITLE
Attempts counter is not updated upon reset

### ISSUE THREAD

**Issue by wtrombone** [topeterk/HitCounterManager#16]
When I'm resetting the run, everything is working fine except attempts counter is not being updated.

 - OS: Windows 10
 - Version: the last one (1.20)

**Comment by topeterk** [comment]
Hi, does this happen always on your side?
Does it happen via reset button or hotkey or both?
I am just wondering because it always worked for me so far.

**Comment by wtrombone** [comment]
It worked before, but stopped working recently, Yes, it happens always. I'm using the hotkey for resetting the run. I even tried installing the separate copy of the software into the different folder, the issue is still there.

**Comment by topeterk** [comment]
Do you know or can you check if setting the counter value manually is working or maybe even "fix" the issue?

**Comment by topeterk** [comment]
I'll close this issue for now as there was no reaction for a longer period of time.
