### ISSUE TITLE
Death Counter Hotkeys

### ISSUE THREAD

**Issue by sivtotherescue** [topeterk/HitCounterManager#17]
I looked through all the settings and I want to use this amazing program for deaths (for now). However I can't seem to figure out how to count deaths and what settings I need for that.

**Comment by topeterk** [comment]
Hi, as I am not exactly sure where you are struggling at, maybe you are looking for the [behavior](../wiki#behavior) setting?
You can change it to use it for no death runs or for counting deaths (more or less without split, just as a counter). If this is not what you asked for, I guess you can use it just like for a no hit run? (Pressing hit button only on deaths rather hits). I hope this helps or you need to be more specific what is kind of missing.

**Comment by sivtotherescue** [comment]
Hi,
Thank you so much for getting back to me! I'm pretty sure it's on my side
anyway, but I read through several threads and videos and can't seem to
find the answer.
I set it to death counter already and it displays all correct. But how do I
make the death counter count up? Isn't there a hotkey for that?
Regards (and much health),
Siv

Peter Kirmeier ***@***.***> schrieb am Di., 30. März 2021,
06:32:

**Comment by sivtotherescue** [comment]
Hello
I'm really sorry, maybe I'm blind... But where do I set the hotkey to count
deaths?
[image: image.png]

Am Di., 30. März 2021 um 16:04 Uhr schrieb Peter Kirmeier <
***@***.***>:

**Comment by topeterk** [comment]
The tool itself does not make any difference between hits or deaths. You should be fine using the "Hit (boss)" hotkey. The difference is only made when the finals table is shown by just displaying a different row title.

**Comment by sivtotherescue** [comment]
Okay thank you very much! I figured it out now ☺️ thank you so much for
creating this amazing tool and helping me! Happy easter and stay safe!

Peter Kirmeier ***@***.***> schrieb am Fr., 2. Apr. 2021,
10:36:

**Comment by topeterk** [comment]
Thank you. You're welcome. :)
