### ISSUE TITLE
Hit Counter Scrolling

### ISSUE THREAD

**Issue by TheRenegadist** [topeterk/HitCounterManager#18]
Currently I have 74 splits set up but once I get to about 16 it continues without showing anything and the only way I can get it to show is if I set the source to something like 800x2500 which is really small when you adjust it for the window.

Can you make it so it scrolls when reaching the bottom while keeping the Split and Run, and Progress Bar static?

**Comment by topeterk** [comment]
Hi, what you are looking for is the "show the last/next .. splits" in the [behavior settings](../wiki#behavior). Just enter the amount of splits the should be sown before/after your current split. This should act like your mentioned "scrolling" effect.

**Comment by topeterk** [comment]
As there was no further question, I guess it worked. So, I'll close this issue for now.
