### ISSUE TITLE
Cannot install .NET framework if a later version is installed

### ISSUE THREAD

**Issue by jhobz** [topeterk/HitCounterManager#19]
**Describe the bug**
When trying to install the HitCounterManager via the `.msi` file, I get this error:
![image](https://user-images.githubusercontent.com/1765799/119752072-4f3ada80-be6a-11eb-94b9-916aeca7f7c1.png)

Upon selecting "Yes" and downloading and running the installer for the .NET framework, it says the framework cannot be installed because a more recent version already exists. As far as I can tell, there is no good way to install an older version.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome Version 90.0.4430.212 (although not relevant here)

**Comment by topeterk** [comment]
Hi, interesting as I haven't expected this prompt either.
I will have a look, maybe I find any wrong setting for the installer.

You can, however, try to run and use the portable version instead which at the moment is this one here: [HitCounterManager_Windows_Portable_v1.20.0.0.zip](https://github.com/topeterk/HitCounterManager/releases/download/1.20.0.0/HitCounterManager_Windows_Portable_v1.20.0.0.zip)
Extract it anywhere you want on your computer and just run the exe file manually. The installer doesn't do much more than check for the .net framework, copying the files to an directory and place a shortcut at the start menu and/or the desktop. So using the portable version is just as fine.

**Comment by jhobz** [comment]
For the record, I finally got around to it and the portable version indeed is working just fine on my system.

**Comment by topeterk** [comment]
As there is a workaround and newer major versions have to be based on another framework anyway, I will close this issue here.
