### ISSUE TITLE
PB hits just stop on first split with hit

### ISSUE THREAD

**Issue by hielfx** [topeterk/HitCounterManager#22]
How can I set the behahiour so the PB will display like this:

![splits](https://raw.githubusercontent.com/wiki/topeterk/HitCounterManager/Images/v1.17.0.0_Sample_Web_NumericNonTransparent.png)

I'm talking about the PB hit colum. In my case, the PB colum just stops on the first split with hits, i.e., all of the next splits, even if they don't have a hit, will be crossed instead of checked. In the image example, all of them will be crossed after the dancer hit.

EDIT: Adding an example file of the case I'm talking about

![output](https://cdn.discordapp.com/attachments/250046807772495875/879411127627436052/Captura.PNG)

**Comment by topeterk** [comment]
Hi, a refactoring of the HTML file brought this issue into version 1.20.

Crossing the PB after the "first" hit should only be done when the purpose option is set to "NoDeath".
You should be able to fix this by opening the file **Designs/HitCounterGui.html**, find...
`ShowCrossOrCheckMark(s.hitless_pb ? s.hits_pb : 1))`
and replace it with
`ShowCrossOrCheckMark(d.purpose == 3 && !s.hitless_pb ? 1 : s.hits_pb))`

I'll add this fix to the next version. Thanks for the feedback ;)
