### ISSUE TITLE
Global shortcuts (OS not supported) - Windows 10 Pro

### ISSUE THREAD

**Issue by SpacePug35** [topeterk/HitCounterManager#23]
I just installed Hit Counter Manager and ran into an issue with the shortcuts.
If I go into settings > Global shortcuts all the shortcuts and tick boxes are greyed out with the text inside stating:
"ERROR: SJIFT + ?"
In the tab Global shortcuts it tells me 'Global Shortcuts(OS not supported)

The program runs fine other than than.

Screenshot:
![Hit](https://user-images.githubusercontent.com/89594813/130988759-c811e940-12cd-4892-ae6b-ecb3110b8927.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Opera GX
 - Version: 20H2

Any help would be appreciated, as the shortcut functionality is most important!

**Comment by topeterk** [comment]
As I think this issue is outdated, I will close it.
